calibration:
  ros__parameters:
    # 世界坐标点配置
    world_points:
      self_fortress: [5.471, -7.5, 0.0]
      self_tower: [10.936, -11.161, 0.868]
      enemy_base: [25.49, -7.5, 1.24524]
      enemy_tower: [16.925, -3.625, 1.745]
      enemy_high: [20.20, -10.8, 0.8]
    
    # 窗口配置
    window:
      main_width: 1440
      main_height: 900
      main_pos_x: 1920-1440
      main_pos_y: 1080-900
      roi_size: 400
    
    # 图像处理配置
    image:
      target_width: 1536
      target_height: 1125
      scale_factor: 1.3333333333
    
    # 标定参数
    calibration:
      pnp_method: "EPNP"
      output_path: "./config/out_matrix.yaml"